services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./docker-init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-init-db/import-data.sh:/docker-entrypoint-initdb.d/import-data.sh
      - ./productData.csv:/var/lib/postgresql/productData.csv
      - postgres_data:/var/lib/postgresql/data
    command: >
      bash -c "
        chmod +x /docker-entrypoint-initdb.d/import-data.sh &&
        docker-entrypoint.sh postgres
      "
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 60s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order_inventory_api
    restart: always
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=postgres;Username=postgres;Password=12345;
    ports:
      - "8080:8080"

volumes:
  postgres_data: